version: '3.8'  # Specify the Compose file version

services:
  omni:
    build:  # Build the image from a Dockerfile
      context: .  # Path to the Dockerfile (usually the current directory)
      dockerfile: Dockerfile  # Name of the Dockerfile if not named 'Dockerfile'
      args:
        user_id: 2000  # Set the user_id argument here

    image: ros1_image  # Name the image to be built
    container_name: ros1_container  # Optional: name the container
    privileged: true  # Use privileged mode
    network_mode: host  # Use host network
    volumes:
      - /home/${USER}/ros1_docker/flightSoftware:/opt/ros/noetic/flightSoftware  # Bind mount for the flightSoftware directory

    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/i2c-1:/dev/i2c-1"      # Ensure access to I2C device

    tty: true  # Allocate a pseudo-TTY for interactive sessions
    stdin_open: true  # Keep stdin open for the container

