# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from omni_firmware/errorMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class errorMsg(genpy.Message):
  _md5sum = "aca7c5154e5df4742f8034562501f6c5"
  _type = "omni_firmware/errorMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Vector3 ex
geometry_msgs/Vector3 ev
geometry_msgs/Vector3 ea
geometry_msgs/Vector3 eR
geometry_msgs/Vector3 ew
geometry_msgs/Vector3 Iex
geometry_msgs/Vector3 Ier
geometry_msgs/Vector3 Accd
float32[] Wrench
float32[] exWrench
float32[] prop
float32 weight

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['ex','ev','ea','eR','ew','Iex','Ier','Accd','Wrench','exWrench','prop','weight']
  _slot_types = ['geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','float32[]','float32[]','float32[]','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ex,ev,ea,eR,ew,Iex,Ier,Accd,Wrench,exWrench,prop,weight

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(errorMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ex is None:
        self.ex = geometry_msgs.msg.Vector3()
      if self.ev is None:
        self.ev = geometry_msgs.msg.Vector3()
      if self.ea is None:
        self.ea = geometry_msgs.msg.Vector3()
      if self.eR is None:
        self.eR = geometry_msgs.msg.Vector3()
      if self.ew is None:
        self.ew = geometry_msgs.msg.Vector3()
      if self.Iex is None:
        self.Iex = geometry_msgs.msg.Vector3()
      if self.Ier is None:
        self.Ier = geometry_msgs.msg.Vector3()
      if self.Accd is None:
        self.Accd = geometry_msgs.msg.Vector3()
      if self.Wrench is None:
        self.Wrench = []
      if self.exWrench is None:
        self.exWrench = []
      if self.prop is None:
        self.prop = []
      if self.weight is None:
        self.weight = 0.
    else:
      self.ex = geometry_msgs.msg.Vector3()
      self.ev = geometry_msgs.msg.Vector3()
      self.ea = geometry_msgs.msg.Vector3()
      self.eR = geometry_msgs.msg.Vector3()
      self.ew = geometry_msgs.msg.Vector3()
      self.Iex = geometry_msgs.msg.Vector3()
      self.Ier = geometry_msgs.msg.Vector3()
      self.Accd = geometry_msgs.msg.Vector3()
      self.Wrench = []
      self.exWrench = []
      self.prop = []
      self.weight = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_24d().pack(_x.ex.x, _x.ex.y, _x.ex.z, _x.ev.x, _x.ev.y, _x.ev.z, _x.ea.x, _x.ea.y, _x.ea.z, _x.eR.x, _x.eR.y, _x.eR.z, _x.ew.x, _x.ew.y, _x.ew.z, _x.Iex.x, _x.Iex.y, _x.Iex.z, _x.Ier.x, _x.Ier.y, _x.Ier.z, _x.Accd.x, _x.Accd.y, _x.Accd.z))
      length = len(self.Wrench)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.Wrench))
      length = len(self.exWrench)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.exWrench))
      length = len(self.prop)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.prop))
      _x = self.weight
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.ex is None:
        self.ex = geometry_msgs.msg.Vector3()
      if self.ev is None:
        self.ev = geometry_msgs.msg.Vector3()
      if self.ea is None:
        self.ea = geometry_msgs.msg.Vector3()
      if self.eR is None:
        self.eR = geometry_msgs.msg.Vector3()
      if self.ew is None:
        self.ew = geometry_msgs.msg.Vector3()
      if self.Iex is None:
        self.Iex = geometry_msgs.msg.Vector3()
      if self.Ier is None:
        self.Ier = geometry_msgs.msg.Vector3()
      if self.Accd is None:
        self.Accd = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 192
      (_x.ex.x, _x.ex.y, _x.ex.z, _x.ev.x, _x.ev.y, _x.ev.z, _x.ea.x, _x.ea.y, _x.ea.z, _x.eR.x, _x.eR.y, _x.eR.z, _x.ew.x, _x.ew.y, _x.ew.z, _x.Iex.x, _x.Iex.y, _x.Iex.z, _x.Ier.x, _x.Ier.y, _x.Ier.z, _x.Accd.x, _x.Accd.y, _x.Accd.z,) = _get_struct_24d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Wrench = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.exWrench = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.prop = s.unpack(str[start:end])
      start = end
      end += 4
      (self.weight,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_24d().pack(_x.ex.x, _x.ex.y, _x.ex.z, _x.ev.x, _x.ev.y, _x.ev.z, _x.ea.x, _x.ea.y, _x.ea.z, _x.eR.x, _x.eR.y, _x.eR.z, _x.ew.x, _x.ew.y, _x.ew.z, _x.Iex.x, _x.Iex.y, _x.Iex.z, _x.Ier.x, _x.Ier.y, _x.Ier.z, _x.Accd.x, _x.Accd.y, _x.Accd.z))
      length = len(self.Wrench)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.Wrench.tostring())
      length = len(self.exWrench)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.exWrench.tostring())
      length = len(self.prop)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.prop.tostring())
      _x = self.weight
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.ex is None:
        self.ex = geometry_msgs.msg.Vector3()
      if self.ev is None:
        self.ev = geometry_msgs.msg.Vector3()
      if self.ea is None:
        self.ea = geometry_msgs.msg.Vector3()
      if self.eR is None:
        self.eR = geometry_msgs.msg.Vector3()
      if self.ew is None:
        self.ew = geometry_msgs.msg.Vector3()
      if self.Iex is None:
        self.Iex = geometry_msgs.msg.Vector3()
      if self.Ier is None:
        self.Ier = geometry_msgs.msg.Vector3()
      if self.Accd is None:
        self.Accd = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 192
      (_x.ex.x, _x.ex.y, _x.ex.z, _x.ev.x, _x.ev.y, _x.ev.z, _x.ea.x, _x.ea.y, _x.ea.z, _x.eR.x, _x.eR.y, _x.eR.z, _x.ew.x, _x.ew.y, _x.ew.z, _x.Iex.x, _x.Iex.y, _x.Iex.z, _x.Ier.x, _x.Ier.y, _x.Ier.z, _x.Accd.x, _x.Accd.y, _x.Accd.z,) = _get_struct_24d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Wrench = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.exWrench = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.prop = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (self.weight,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_24d = None
def _get_struct_24d():
    global _struct_24d
    if _struct_24d is None:
        _struct_24d = struct.Struct("<24d")
    return _struct_24d
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
