# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from maneuver/Ellipse5DRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Ellipse5DRequest(genpy.Message):
  _md5sum = "de591e0b342372a5677c5ef03c671935"
  _type = "maneuver/Ellipse5DRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 x_min
float32 x_max
float32 y_min
float32 y_max
float32 z_min
float32 z_max
float32 roll_start
float32 roll_mid
float32 roll_end
float32 pitch_start
float32 pitch_mid
float32 pitch_end
float32 yaw
float32 duration
"""
  __slots__ = ['x_min','x_max','y_min','y_max','z_min','z_max','roll_start','roll_mid','roll_end','pitch_start','pitch_mid','pitch_end','yaw','duration']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x_min,x_max,y_min,y_max,z_min,z_max,roll_start,roll_mid,roll_end,pitch_start,pitch_mid,pitch_end,yaw,duration

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Ellipse5DRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x_min is None:
        self.x_min = 0.
      if self.x_max is None:
        self.x_max = 0.
      if self.y_min is None:
        self.y_min = 0.
      if self.y_max is None:
        self.y_max = 0.
      if self.z_min is None:
        self.z_min = 0.
      if self.z_max is None:
        self.z_max = 0.
      if self.roll_start is None:
        self.roll_start = 0.
      if self.roll_mid is None:
        self.roll_mid = 0.
      if self.roll_end is None:
        self.roll_end = 0.
      if self.pitch_start is None:
        self.pitch_start = 0.
      if self.pitch_mid is None:
        self.pitch_mid = 0.
      if self.pitch_end is None:
        self.pitch_end = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.duration is None:
        self.duration = 0.
    else:
      self.x_min = 0.
      self.x_max = 0.
      self.y_min = 0.
      self.y_max = 0.
      self.z_min = 0.
      self.z_max = 0.
      self.roll_start = 0.
      self.roll_mid = 0.
      self.roll_end = 0.
      self.pitch_start = 0.
      self.pitch_mid = 0.
      self.pitch_end = 0.
      self.yaw = 0.
      self.duration = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_14f().pack(_x.x_min, _x.x_max, _x.y_min, _x.y_max, _x.z_min, _x.z_max, _x.roll_start, _x.roll_mid, _x.roll_end, _x.pitch_start, _x.pitch_mid, _x.pitch_end, _x.yaw, _x.duration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.x_min, _x.x_max, _x.y_min, _x.y_max, _x.z_min, _x.z_max, _x.roll_start, _x.roll_mid, _x.roll_end, _x.pitch_start, _x.pitch_mid, _x.pitch_end, _x.yaw, _x.duration,) = _get_struct_14f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_14f().pack(_x.x_min, _x.x_max, _x.y_min, _x.y_max, _x.z_min, _x.z_max, _x.roll_start, _x.roll_mid, _x.roll_end, _x.pitch_start, _x.pitch_mid, _x.pitch_end, _x.yaw, _x.duration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.x_min, _x.x_max, _x.y_min, _x.y_max, _x.z_min, _x.z_max, _x.roll_start, _x.roll_mid, _x.roll_end, _x.pitch_start, _x.pitch_mid, _x.pitch_end, _x.yaw, _x.duration,) = _get_struct_14f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_14f = None
def _get_struct_14f():
    global _struct_14f
    if _struct_14f is None:
        _struct_14f = struct.Struct("<14f")
    return _struct_14f
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from maneuver/Ellipse5DResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Ellipse5DResponse(genpy.Message):
  _md5sum = "3a1255d4d998bd4d6585c64639b5ee9a"
  _type = "maneuver/Ellipse5DResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool status

"""
  __slots__ = ['status']
  _slot_types = ['bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Ellipse5DResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.status is None:
        self.status = False
    else:
      self.status = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.status
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.status,) = _get_struct_B().unpack(str[start:end])
      self.status = bool(self.status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.status
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.status,) = _get_struct_B().unpack(str[start:end])
      self.status = bool(self.status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class Ellipse5D(object):
  _type          = 'maneuver/Ellipse5D'
  _md5sum = 'bdb0ce274c1da7c8239ea3857b021bbb'
  _request_class  = Ellipse5DRequest
  _response_class = Ellipse5DResponse
