(cl:in-package maneuver-srv)
(cl:export '(X_MIN-VAL
          X_MIN
          X_MAX-VAL
          X_MAX
          Y_MIN-VAL
          Y_MIN
          Y_MAX-VAL
          Y_MAX
          Z_MIN-VAL
          Z_MIN
          Z_MAX-VAL
          Z_MAX
          ROLL_START-VAL
          ROLL_START
          ROLL_MID-VAL
          ROLL_MID
          ROLL_END-VAL
          ROLL_END
          PITCH_START-VAL
          PITCH_START
          PITCH_MID-VAL
          PITCH_MID
          PITCH_END-VAL
          PITCH_END
          YAW-VAL
          YAW
          DURATION-VAL
          DURATION
          STATUS-VAL
          STATUS
))