// Generated by gencpp from file servo_control_node/ReleaseArms.msg
// DO NOT EDIT!


#ifndef SERVO_CONTROL_NODE_MESSAGE_RELEASEARMS_H
#define SERVO_CONTROL_NODE_MESSAGE_RELEASEARMS_H

#include <ros/service_traits.h>


#include <servo_control_node/ReleaseArmsRequest.h>
#include <servo_control_node/ReleaseArmsResponse.h>


namespace servo_control_node
{

struct ReleaseArms
{

typedef ReleaseArmsRequest Request;
typedef ReleaseArmsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReleaseArms
} // namespace servo_control_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::servo_control_node::ReleaseArms > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::servo_control_node::ReleaseArms&) { return value(); }
};

template<>
struct DataType< ::servo_control_node::ReleaseArms > {
  static const char* value()
  {
    return "servo_control_node/ReleaseArms";
  }

  static const char* value(const ::servo_control_node::ReleaseArms&) { return value(); }
};


// service_traits::MD5Sum< ::servo_control_node::ReleaseArmsRequest> should match
// service_traits::MD5Sum< ::servo_control_node::ReleaseArms >
template<>
struct MD5Sum< ::servo_control_node::ReleaseArmsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::servo_control_node::ReleaseArms >::value();
  }
  static const char* value(const ::servo_control_node::ReleaseArmsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::servo_control_node::ReleaseArmsRequest> should match
// service_traits::DataType< ::servo_control_node::ReleaseArms >
template<>
struct DataType< ::servo_control_node::ReleaseArmsRequest>
{
  static const char* value()
  {
    return DataType< ::servo_control_node::ReleaseArms >::value();
  }
  static const char* value(const ::servo_control_node::ReleaseArmsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::servo_control_node::ReleaseArmsResponse> should match
// service_traits::MD5Sum< ::servo_control_node::ReleaseArms >
template<>
struct MD5Sum< ::servo_control_node::ReleaseArmsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::servo_control_node::ReleaseArms >::value();
  }
  static const char* value(const ::servo_control_node::ReleaseArmsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::servo_control_node::ReleaseArmsResponse> should match
// service_traits::DataType< ::servo_control_node::ReleaseArms >
template<>
struct DataType< ::servo_control_node::ReleaseArmsResponse>
{
  static const char* value()
  {
    return DataType< ::servo_control_node::ReleaseArms >::value();
  }
  static const char* value(const ::servo_control_node::ReleaseArmsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVO_CONTROL_NODE_MESSAGE_RELEASEARMS_H
