// Generated by gencpp from file servo_control_node/ReleaseArmsRequest.msg
// DO NOT EDIT!


#ifndef SERVO_CONTROL_NODE_MESSAGE_RELEASEARMSREQUEST_H
#define SERVO_CONTROL_NODE_MESSAGE_RELEASEARMSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_control_node
{
template <class ContainerAllocator>
struct ReleaseArmsRequest_
{
  typedef ReleaseArmsRequest_<ContainerAllocator> Type;

  ReleaseArmsRequest_()
    {
    }
  ReleaseArmsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReleaseArmsRequest_

typedef ::servo_control_node::ReleaseArmsRequest_<std::allocator<void> > ReleaseArmsRequest;

typedef boost::shared_ptr< ::servo_control_node::ReleaseArmsRequest > ReleaseArmsRequestPtr;
typedef boost::shared_ptr< ::servo_control_node::ReleaseArmsRequest const> ReleaseArmsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace servo_control_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_control_node/ReleaseArmsRequest";
  }

  static const char* value(const ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReleaseArmsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::servo_control_node::ReleaseArmsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_CONTROL_NODE_MESSAGE_RELEASEARMSREQUEST_H
