// Generated by gencpp from file servo_control_node/SetAnglesResponse.msg
// DO NOT EDIT!


#ifndef SERVO_CONTROL_NODE_MESSAGE_SETANGLESRESPONSE_H
#define SERVO_CONTROL_NODE_MESSAGE_SETANGLESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_control_node
{
template <class ContainerAllocator>
struct SetAnglesResponse_
{
  typedef SetAnglesResponse_<ContainerAllocator> Type;

  SetAnglesResponse_()
    : success(false)  {
    }
  SetAnglesResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::servo_control_node::SetAnglesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_control_node::SetAnglesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetAnglesResponse_

typedef ::servo_control_node::SetAnglesResponse_<std::allocator<void> > SetAnglesResponse;

typedef boost::shared_ptr< ::servo_control_node::SetAnglesResponse > SetAnglesResponsePtr;
typedef boost::shared_ptr< ::servo_control_node::SetAnglesResponse const> SetAnglesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_control_node::SetAnglesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_control_node::SetAnglesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servo_control_node::SetAnglesResponse_<ContainerAllocator1> & lhs, const ::servo_control_node::SetAnglesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servo_control_node::SetAnglesResponse_<ContainerAllocator1> & lhs, const ::servo_control_node::SetAnglesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servo_control_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::servo_control_node::SetAnglesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_control_node::SetAnglesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_control_node::SetAnglesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_control_node::SetAnglesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control_node::SetAnglesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control_node::SetAnglesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_control_node::SetAnglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::servo_control_node::SetAnglesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_control_node::SetAnglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_control_node/SetAnglesResponse";
  }

  static const char* value(const ::servo_control_node::SetAnglesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_control_node::SetAnglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success  # Return success if the operation was successful\n"
"\n"
"\n"
;
  }

  static const char* value(const ::servo_control_node::SetAnglesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_control_node::SetAnglesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetAnglesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_control_node::SetAnglesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo_control_node::SetAnglesResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_CONTROL_NODE_MESSAGE_SETANGLESRESPONSE_H
