// Generated by gencpp from file servo_control_node/SetAnglesRequest.msg
// DO NOT EDIT!


#ifndef SERVO_CONTROL_NODE_MESSAGE_SETANGLESREQUEST_H
#define SERVO_CONTROL_NODE_MESSAGE_SETANGLESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_control_node
{
template <class ContainerAllocator>
struct SetAnglesRequest_
{
  typedef SetAnglesRequest_<ContainerAllocator> Type;

  SetAnglesRequest_()
    : right(0)
    , left(0)  {
    }
  SetAnglesRequest_(const ContainerAllocator& _alloc)
    : right(0)
    , left(0)  {
  (void)_alloc;
    }



   typedef int32_t _right_type;
  _right_type right;

   typedef int32_t _left_type;
  _left_type left;





  typedef boost::shared_ptr< ::servo_control_node::SetAnglesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_control_node::SetAnglesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetAnglesRequest_

typedef ::servo_control_node::SetAnglesRequest_<std::allocator<void> > SetAnglesRequest;

typedef boost::shared_ptr< ::servo_control_node::SetAnglesRequest > SetAnglesRequestPtr;
typedef boost::shared_ptr< ::servo_control_node::SetAnglesRequest const> SetAnglesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_control_node::SetAnglesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_control_node::SetAnglesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servo_control_node::SetAnglesRequest_<ContainerAllocator1> & lhs, const ::servo_control_node::SetAnglesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.right == rhs.right &&
    lhs.left == rhs.left;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servo_control_node::SetAnglesRequest_<ContainerAllocator1> & lhs, const ::servo_control_node::SetAnglesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servo_control_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::servo_control_node::SetAnglesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_control_node::SetAnglesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_control_node::SetAnglesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_control_node::SetAnglesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control_node::SetAnglesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control_node::SetAnglesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_control_node::SetAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56e15b137f05b503f692a3beaa4e3f7a";
  }

  static const char* value(const ::servo_control_node::SetAnglesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56e15b137f05b503ULL;
  static const uint64_t static_value2 = 0xf692a3beaa4e3f7aULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_control_node::SetAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_control_node/SetAnglesRequest";
  }

  static const char* value(const ::servo_control_node::SetAnglesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_control_node::SetAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# srv/SetAngles.srv\n"
"\n"
"int32 right   # Angle for the right motor\n"
"int32 left    # Angle for the left motor\n"
;
  }

  static const char* value(const ::servo_control_node::SetAnglesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_control_node::SetAnglesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.right);
      stream.next(m.left);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetAnglesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_control_node::SetAnglesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo_control_node::SetAnglesRequest_<ContainerAllocator>& v)
  {
    s << indent << "right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right);
    s << indent << "left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_CONTROL_NODE_MESSAGE_SETANGLESREQUEST_H
