// Generated by gencpp from file servo_control_node/SetAngles.msg
// DO NOT EDIT!


#ifndef SERVO_CONTROL_NODE_MESSAGE_SETANGLES_H
#define SERVO_CONTROL_NODE_MESSAGE_SETANGLES_H

#include <ros/service_traits.h>


#include <servo_control_node/SetAnglesRequest.h>
#include <servo_control_node/SetAnglesResponse.h>


namespace servo_control_node
{

struct SetAngles
{

typedef SetAnglesRequest Request;
typedef SetAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAngles
} // namespace servo_control_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::servo_control_node::SetAngles > {
  static const char* value()
  {
    return "af6660be3609fe9894731472db7c883b";
  }

  static const char* value(const ::servo_control_node::SetAngles&) { return value(); }
};

template<>
struct DataType< ::servo_control_node::SetAngles > {
  static const char* value()
  {
    return "servo_control_node/SetAngles";
  }

  static const char* value(const ::servo_control_node::SetAngles&) { return value(); }
};


// service_traits::MD5Sum< ::servo_control_node::SetAnglesRequest> should match
// service_traits::MD5Sum< ::servo_control_node::SetAngles >
template<>
struct MD5Sum< ::servo_control_node::SetAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::servo_control_node::SetAngles >::value();
  }
  static const char* value(const ::servo_control_node::SetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::servo_control_node::SetAnglesRequest> should match
// service_traits::DataType< ::servo_control_node::SetAngles >
template<>
struct DataType< ::servo_control_node::SetAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::servo_control_node::SetAngles >::value();
  }
  static const char* value(const ::servo_control_node::SetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::servo_control_node::SetAnglesResponse> should match
// service_traits::MD5Sum< ::servo_control_node::SetAngles >
template<>
struct MD5Sum< ::servo_control_node::SetAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::servo_control_node::SetAngles >::value();
  }
  static const char* value(const ::servo_control_node::SetAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::servo_control_node::SetAnglesResponse> should match
// service_traits::DataType< ::servo_control_node::SetAngles >
template<>
struct DataType< ::servo_control_node::SetAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::servo_control_node::SetAngles >::value();
  }
  static const char* value(const ::servo_control_node::SetAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVO_CONTROL_NODE_MESSAGE_SETANGLES_H
