// Generated by gencpp from file controller/AngularWrenchRequest.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_ANGULARWRENCHREQUEST_H
#define CONTROLLER_MESSAGE_ANGULARWRENCHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller
{
template <class ContainerAllocator>
struct AngularWrenchRequest_
{
  typedef AngularWrenchRequest_<ContainerAllocator> Type;

  AngularWrenchRequest_()
    : fz(0.0)
    , phi1(0.0)
    , phi2(0.0)
    , duration(0.0)  {
    }
  AngularWrenchRequest_(const ContainerAllocator& _alloc)
    : fz(0.0)
    , phi1(0.0)
    , phi2(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef float _fz_type;
  _fz_type fz;

   typedef float _phi1_type;
  _phi1_type phi1;

   typedef float _phi2_type;
  _phi2_type phi2;

   typedef float _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::controller::AngularWrenchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::AngularWrenchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AngularWrenchRequest_

typedef ::controller::AngularWrenchRequest_<std::allocator<void> > AngularWrenchRequest;

typedef boost::shared_ptr< ::controller::AngularWrenchRequest > AngularWrenchRequestPtr;
typedef boost::shared_ptr< ::controller::AngularWrenchRequest const> AngularWrenchRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller::AngularWrenchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller::AngularWrenchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller::AngularWrenchRequest_<ContainerAllocator1> & lhs, const ::controller::AngularWrenchRequest_<ContainerAllocator2> & rhs)
{
  return lhs.fz == rhs.fz &&
    lhs.phi1 == rhs.phi1 &&
    lhs.phi2 == rhs.phi2 &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller::AngularWrenchRequest_<ContainerAllocator1> & lhs, const ::controller::AngularWrenchRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::controller::AngularWrenchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::AngularWrenchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::AngularWrenchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::AngularWrenchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::AngularWrenchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::AngularWrenchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller::AngularWrenchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc9e7d68423879ad0d9a0703c727a1f6";
  }

  static const char* value(const ::controller::AngularWrenchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc9e7d68423879adULL;
  static const uint64_t static_value2 = 0x0d9a0703c727a1f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::AngularWrenchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller/AngularWrenchRequest";
  }

  static const char* value(const ::controller::AngularWrenchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller::AngularWrenchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 fz\n"
"float32 phi1\n"
"float32 phi2\n"
"float32 duration\n"
;
  }

  static const char* value(const ::controller::AngularWrenchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller::AngularWrenchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fz);
      stream.next(m.phi1);
      stream.next(m.phi2);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AngularWrenchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::AngularWrenchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller::AngularWrenchRequest_<ContainerAllocator>& v)
  {
    s << indent << "fz: ";
    Printer<float>::stream(s, indent + "  ", v.fz);
    s << indent << "phi1: ";
    Printer<float>::stream(s, indent + "  ", v.phi1);
    s << indent << "phi2: ";
    Printer<float>::stream(s, indent + "  ", v.phi2);
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_ANGULARWRENCHREQUEST_H
