// Generated by gencpp from file controller/AngularWrench.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_ANGULARWRENCH_H
#define CONTROLLER_MESSAGE_ANGULARWRENCH_H

#include <ros/service_traits.h>


#include <controller/AngularWrenchRequest.h>
#include <controller/AngularWrenchResponse.h>


namespace controller
{

struct AngularWrench
{

typedef AngularWrenchRequest Request;
typedef AngularWrenchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AngularWrench
} // namespace controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::controller::AngularWrench > {
  static const char* value()
  {
    return "bfbfde29636da2ef0700941fae523d7c";
  }

  static const char* value(const ::controller::AngularWrench&) { return value(); }
};

template<>
struct DataType< ::controller::AngularWrench > {
  static const char* value()
  {
    return "controller/AngularWrench";
  }

  static const char* value(const ::controller::AngularWrench&) { return value(); }
};


// service_traits::MD5Sum< ::controller::AngularWrenchRequest> should match
// service_traits::MD5Sum< ::controller::AngularWrench >
template<>
struct MD5Sum< ::controller::AngularWrenchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::controller::AngularWrench >::value();
  }
  static const char* value(const ::controller::AngularWrenchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller::AngularWrenchRequest> should match
// service_traits::DataType< ::controller::AngularWrench >
template<>
struct DataType< ::controller::AngularWrenchRequest>
{
  static const char* value()
  {
    return DataType< ::controller::AngularWrench >::value();
  }
  static const char* value(const ::controller::AngularWrenchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::controller::AngularWrenchResponse> should match
// service_traits::MD5Sum< ::controller::AngularWrench >
template<>
struct MD5Sum< ::controller::AngularWrenchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::controller::AngularWrench >::value();
  }
  static const char* value(const ::controller::AngularWrenchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller::AngularWrenchResponse> should match
// service_traits::DataType< ::controller::AngularWrench >
template<>
struct DataType< ::controller::AngularWrenchResponse>
{
  static const char* value()
  {
    return DataType< ::controller::AngularWrench >::value();
  }
  static const char* value(const ::controller::AngularWrenchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROLLER_MESSAGE_ANGULARWRENCH_H
