// Generated by gencpp from file controller/LinearWrenchRequest.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_LINEARWRENCHREQUEST_H
#define CONTROLLER_MESSAGE_LINEARWRENCHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller
{
template <class ContainerAllocator>
struct LinearWrenchRequest_
{
  typedef LinearWrenchRequest_<ContainerAllocator> Type;

  LinearWrenchRequest_()
    : fx1(0.0)
    , fy1(0.0)
    , fz1(0.0)
    , fx2(0.0)
    , fy2(0.0)
    , fz2(0.0)
    , ramp(0.0)
    , duration(0.0)  {
    }
  LinearWrenchRequest_(const ContainerAllocator& _alloc)
    : fx1(0.0)
    , fy1(0.0)
    , fz1(0.0)
    , fx2(0.0)
    , fy2(0.0)
    , fz2(0.0)
    , ramp(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef float _fx1_type;
  _fx1_type fx1;

   typedef float _fy1_type;
  _fy1_type fy1;

   typedef float _fz1_type;
  _fz1_type fz1;

   typedef float _fx2_type;
  _fx2_type fx2;

   typedef float _fy2_type;
  _fy2_type fy2;

   typedef float _fz2_type;
  _fz2_type fz2;

   typedef float _ramp_type;
  _ramp_type ramp;

   typedef float _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::controller::LinearWrenchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::LinearWrenchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LinearWrenchRequest_

typedef ::controller::LinearWrenchRequest_<std::allocator<void> > LinearWrenchRequest;

typedef boost::shared_ptr< ::controller::LinearWrenchRequest > LinearWrenchRequestPtr;
typedef boost::shared_ptr< ::controller::LinearWrenchRequest const> LinearWrenchRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller::LinearWrenchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller::LinearWrenchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller::LinearWrenchRequest_<ContainerAllocator1> & lhs, const ::controller::LinearWrenchRequest_<ContainerAllocator2> & rhs)
{
  return lhs.fx1 == rhs.fx1 &&
    lhs.fy1 == rhs.fy1 &&
    lhs.fz1 == rhs.fz1 &&
    lhs.fx2 == rhs.fx2 &&
    lhs.fy2 == rhs.fy2 &&
    lhs.fz2 == rhs.fz2 &&
    lhs.ramp == rhs.ramp &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller::LinearWrenchRequest_<ContainerAllocator1> & lhs, const ::controller::LinearWrenchRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::controller::LinearWrenchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::LinearWrenchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::LinearWrenchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::LinearWrenchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::LinearWrenchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::LinearWrenchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller::LinearWrenchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c003c250150c4e771ba847e7b69d707d";
  }

  static const char* value(const ::controller::LinearWrenchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc003c250150c4e77ULL;
  static const uint64_t static_value2 = 0x1ba847e7b69d707dULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::LinearWrenchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller/LinearWrenchRequest";
  }

  static const char* value(const ::controller::LinearWrenchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller::LinearWrenchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 fx1\n"
"float32 fy1\n"
"float32 fz1\n"
"float32 fx2\n"
"float32 fy2\n"
"float32 fz2\n"
"float32 ramp\n"
"float32 duration\n"
;
  }

  static const char* value(const ::controller::LinearWrenchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller::LinearWrenchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fx1);
      stream.next(m.fy1);
      stream.next(m.fz1);
      stream.next(m.fx2);
      stream.next(m.fy2);
      stream.next(m.fz2);
      stream.next(m.ramp);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinearWrenchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::LinearWrenchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller::LinearWrenchRequest_<ContainerAllocator>& v)
  {
    s << indent << "fx1: ";
    Printer<float>::stream(s, indent + "  ", v.fx1);
    s << indent << "fy1: ";
    Printer<float>::stream(s, indent + "  ", v.fy1);
    s << indent << "fz1: ";
    Printer<float>::stream(s, indent + "  ", v.fz1);
    s << indent << "fx2: ";
    Printer<float>::stream(s, indent + "  ", v.fx2);
    s << indent << "fy2: ";
    Printer<float>::stream(s, indent + "  ", v.fy2);
    s << indent << "fz2: ";
    Printer<float>::stream(s, indent + "  ", v.fz2);
    s << indent << "ramp: ";
    Printer<float>::stream(s, indent + "  ", v.ramp);
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_LINEARWRENCHREQUEST_H
