// Generated by gencpp from file controller/LinearWrenchResponse.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_LINEARWRENCHRESPONSE_H
#define CONTROLLER_MESSAGE_LINEARWRENCHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller
{
template <class ContainerAllocator>
struct LinearWrenchResponse_
{
  typedef LinearWrenchResponse_<ContainerAllocator> Type;

  LinearWrenchResponse_()
    : status(false)  {
    }
  LinearWrenchResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::controller::LinearWrenchResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::LinearWrenchResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LinearWrenchResponse_

typedef ::controller::LinearWrenchResponse_<std::allocator<void> > LinearWrenchResponse;

typedef boost::shared_ptr< ::controller::LinearWrenchResponse > LinearWrenchResponsePtr;
typedef boost::shared_ptr< ::controller::LinearWrenchResponse const> LinearWrenchResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller::LinearWrenchResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller::LinearWrenchResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller::LinearWrenchResponse_<ContainerAllocator1> & lhs, const ::controller::LinearWrenchResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller::LinearWrenchResponse_<ContainerAllocator1> & lhs, const ::controller::LinearWrenchResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::controller::LinearWrenchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::LinearWrenchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::LinearWrenchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::LinearWrenchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::LinearWrenchResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::LinearWrenchResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller::LinearWrenchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::controller::LinearWrenchResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::LinearWrenchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller/LinearWrenchResponse";
  }

  static const char* value(const ::controller::LinearWrenchResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller::LinearWrenchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
;
  }

  static const char* value(const ::controller::LinearWrenchResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller::LinearWrenchResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinearWrenchResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::LinearWrenchResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller::LinearWrenchResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_LINEARWRENCHRESPONSE_H
