// Generated by gencpp from file controller/LinearWrench.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_LINEARWRENCH_H
#define CONTROLLER_MESSAGE_LINEARWRENCH_H

#include <ros/service_traits.h>


#include <controller/LinearWrenchRequest.h>
#include <controller/LinearWrenchResponse.h>


namespace controller
{

struct LinearWrench
{

typedef LinearWrenchRequest Request;
typedef LinearWrenchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LinearWrench
} // namespace controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::controller::LinearWrench > {
  static const char* value()
  {
    return "676b2c4049e154bfe83fc0a28e11e13d";
  }

  static const char* value(const ::controller::LinearWrench&) { return value(); }
};

template<>
struct DataType< ::controller::LinearWrench > {
  static const char* value()
  {
    return "controller/LinearWrench";
  }

  static const char* value(const ::controller::LinearWrench&) { return value(); }
};


// service_traits::MD5Sum< ::controller::LinearWrenchRequest> should match
// service_traits::MD5Sum< ::controller::LinearWrench >
template<>
struct MD5Sum< ::controller::LinearWrenchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::controller::LinearWrench >::value();
  }
  static const char* value(const ::controller::LinearWrenchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller::LinearWrenchRequest> should match
// service_traits::DataType< ::controller::LinearWrench >
template<>
struct DataType< ::controller::LinearWrenchRequest>
{
  static const char* value()
  {
    return DataType< ::controller::LinearWrench >::value();
  }
  static const char* value(const ::controller::LinearWrenchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::controller::LinearWrenchResponse> should match
// service_traits::MD5Sum< ::controller::LinearWrench >
template<>
struct MD5Sum< ::controller::LinearWrenchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::controller::LinearWrench >::value();
  }
  static const char* value(const ::controller::LinearWrenchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller::LinearWrenchResponse> should match
// service_traits::DataType< ::controller::LinearWrench >
template<>
struct DataType< ::controller::LinearWrenchResponse>
{
  static const char* value()
  {
    return DataType< ::controller::LinearWrench >::value();
  }
  static const char* value(const ::controller::LinearWrenchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROLLER_MESSAGE_LINEARWRENCH_H
