// Generated by gencpp from file maneuver/ArmDisarmRequest.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_ARMDISARMREQUEST_H
#define MANEUVER_MESSAGE_ARMDISARMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maneuver
{
template <class ContainerAllocator>
struct ArmDisarmRequest_
{
  typedef ArmDisarmRequest_<ContainerAllocator> Type;

  ArmDisarmRequest_()
    {
    }
  ArmDisarmRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::maneuver::ArmDisarmRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maneuver::ArmDisarmRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ArmDisarmRequest_

typedef ::maneuver::ArmDisarmRequest_<std::allocator<void> > ArmDisarmRequest;

typedef boost::shared_ptr< ::maneuver::ArmDisarmRequest > ArmDisarmRequestPtr;
typedef boost::shared_ptr< ::maneuver::ArmDisarmRequest const> ArmDisarmRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maneuver::ArmDisarmRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maneuver::ArmDisarmRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace maneuver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maneuver::ArmDisarmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maneuver::ArmDisarmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::ArmDisarmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::ArmDisarmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::ArmDisarmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::ArmDisarmRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maneuver::ArmDisarmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::maneuver::ArmDisarmRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::maneuver::ArmDisarmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maneuver/ArmDisarmRequest";
  }

  static const char* value(const ::maneuver::ArmDisarmRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maneuver::ArmDisarmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::maneuver::ArmDisarmRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maneuver::ArmDisarmRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmDisarmRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maneuver::ArmDisarmRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::maneuver::ArmDisarmRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MANEUVER_MESSAGE_ARMDISARMREQUEST_H
