// Generated by gencpp from file maneuver/ArmDisarm.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_ARMDISARM_H
#define MANEUVER_MESSAGE_ARMDISARM_H

#include <ros/service_traits.h>


#include <maneuver/ArmDisarmRequest.h>
#include <maneuver/ArmDisarmResponse.h>


namespace maneuver
{

struct ArmDisarm
{

typedef ArmDisarmRequest Request;
typedef ArmDisarmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmDisarm
} // namespace maneuver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maneuver::ArmDisarm > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::maneuver::ArmDisarm&) { return value(); }
};

template<>
struct DataType< ::maneuver::ArmDisarm > {
  static const char* value()
  {
    return "maneuver/ArmDisarm";
  }

  static const char* value(const ::maneuver::ArmDisarm&) { return value(); }
};


// service_traits::MD5Sum< ::maneuver::ArmDisarmRequest> should match
// service_traits::MD5Sum< ::maneuver::ArmDisarm >
template<>
struct MD5Sum< ::maneuver::ArmDisarmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::ArmDisarm >::value();
  }
  static const char* value(const ::maneuver::ArmDisarmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::ArmDisarmRequest> should match
// service_traits::DataType< ::maneuver::ArmDisarm >
template<>
struct DataType< ::maneuver::ArmDisarmRequest>
{
  static const char* value()
  {
    return DataType< ::maneuver::ArmDisarm >::value();
  }
  static const char* value(const ::maneuver::ArmDisarmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maneuver::ArmDisarmResponse> should match
// service_traits::MD5Sum< ::maneuver::ArmDisarm >
template<>
struct MD5Sum< ::maneuver::ArmDisarmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::ArmDisarm >::value();
  }
  static const char* value(const ::maneuver::ArmDisarmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::ArmDisarmResponse> should match
// service_traits::DataType< ::maneuver::ArmDisarm >
template<>
struct DataType< ::maneuver::ArmDisarmResponse>
{
  static const char* value()
  {
    return DataType< ::maneuver::ArmDisarm >::value();
  }
  static const char* value(const ::maneuver::ArmDisarmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANEUVER_MESSAGE_ARMDISARM_H
