// Generated by gencpp from file maneuver/Ellipse5DResponse.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_ELLIPSE5DRESPONSE_H
#define MANEUVER_MESSAGE_ELLIPSE5DRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maneuver
{
template <class ContainerAllocator>
struct Ellipse5DResponse_
{
  typedef Ellipse5DResponse_<ContainerAllocator> Type;

  Ellipse5DResponse_()
    : status(false)  {
    }
  Ellipse5DResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::maneuver::Ellipse5DResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maneuver::Ellipse5DResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Ellipse5DResponse_

typedef ::maneuver::Ellipse5DResponse_<std::allocator<void> > Ellipse5DResponse;

typedef boost::shared_ptr< ::maneuver::Ellipse5DResponse > Ellipse5DResponsePtr;
typedef boost::shared_ptr< ::maneuver::Ellipse5DResponse const> Ellipse5DResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maneuver::Ellipse5DResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maneuver::Ellipse5DResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maneuver::Ellipse5DResponse_<ContainerAllocator1> & lhs, const ::maneuver::Ellipse5DResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maneuver::Ellipse5DResponse_<ContainerAllocator1> & lhs, const ::maneuver::Ellipse5DResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maneuver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maneuver::Ellipse5DResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maneuver::Ellipse5DResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::Ellipse5DResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::Ellipse5DResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::Ellipse5DResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::Ellipse5DResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maneuver::Ellipse5DResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::maneuver::Ellipse5DResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::maneuver::Ellipse5DResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maneuver/Ellipse5DResponse";
  }

  static const char* value(const ::maneuver::Ellipse5DResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maneuver::Ellipse5DResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
;
  }

  static const char* value(const ::maneuver::Ellipse5DResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maneuver::Ellipse5DResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ellipse5DResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maneuver::Ellipse5DResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maneuver::Ellipse5DResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANEUVER_MESSAGE_ELLIPSE5DRESPONSE_H
