// Generated by gencpp from file maneuver/Ellipse5D.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_ELLIPSE5D_H
#define MANEUVER_MESSAGE_ELLIPSE5D_H

#include <ros/service_traits.h>


#include <maneuver/Ellipse5DRequest.h>
#include <maneuver/Ellipse5DResponse.h>


namespace maneuver
{

struct Ellipse5D
{

typedef Ellipse5DRequest Request;
typedef Ellipse5DResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Ellipse5D
} // namespace maneuver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maneuver::Ellipse5D > {
  static const char* value()
  {
    return "bdb0ce274c1da7c8239ea3857b021bbb";
  }

  static const char* value(const ::maneuver::Ellipse5D&) { return value(); }
};

template<>
struct DataType< ::maneuver::Ellipse5D > {
  static const char* value()
  {
    return "maneuver/Ellipse5D";
  }

  static const char* value(const ::maneuver::Ellipse5D&) { return value(); }
};


// service_traits::MD5Sum< ::maneuver::Ellipse5DRequest> should match
// service_traits::MD5Sum< ::maneuver::Ellipse5D >
template<>
struct MD5Sum< ::maneuver::Ellipse5DRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::Ellipse5D >::value();
  }
  static const char* value(const ::maneuver::Ellipse5DRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::Ellipse5DRequest> should match
// service_traits::DataType< ::maneuver::Ellipse5D >
template<>
struct DataType< ::maneuver::Ellipse5DRequest>
{
  static const char* value()
  {
    return DataType< ::maneuver::Ellipse5D >::value();
  }
  static const char* value(const ::maneuver::Ellipse5DRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maneuver::Ellipse5DResponse> should match
// service_traits::MD5Sum< ::maneuver::Ellipse5D >
template<>
struct MD5Sum< ::maneuver::Ellipse5DResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::Ellipse5D >::value();
  }
  static const char* value(const ::maneuver::Ellipse5DResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::Ellipse5DResponse> should match
// service_traits::DataType< ::maneuver::Ellipse5D >
template<>
struct DataType< ::maneuver::Ellipse5DResponse>
{
  static const char* value()
  {
    return DataType< ::maneuver::Ellipse5D >::value();
  }
  static const char* value(const ::maneuver::Ellipse5DResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANEUVER_MESSAGE_ELLIPSE5D_H
