// Generated by gencpp from file maneuver/Ellipse5DRequest.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_ELLIPSE5DREQUEST_H
#define MANEUVER_MESSAGE_ELLIPSE5DREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maneuver
{
template <class ContainerAllocator>
struct Ellipse5DRequest_
{
  typedef Ellipse5DRequest_<ContainerAllocator> Type;

  Ellipse5DRequest_()
    : x_min(0.0)
    , x_max(0.0)
    , y_min(0.0)
    , y_max(0.0)
    , z_min(0.0)
    , z_max(0.0)
    , roll_start(0.0)
    , roll_mid(0.0)
    , roll_end(0.0)
    , pitch_start(0.0)
    , pitch_mid(0.0)
    , pitch_end(0.0)
    , yaw(0.0)
    , duration(0.0)  {
    }
  Ellipse5DRequest_(const ContainerAllocator& _alloc)
    : x_min(0.0)
    , x_max(0.0)
    , y_min(0.0)
    , y_max(0.0)
    , z_min(0.0)
    , z_max(0.0)
    , roll_start(0.0)
    , roll_mid(0.0)
    , roll_end(0.0)
    , pitch_start(0.0)
    , pitch_mid(0.0)
    , pitch_end(0.0)
    , yaw(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef float _x_min_type;
  _x_min_type x_min;

   typedef float _x_max_type;
  _x_max_type x_max;

   typedef float _y_min_type;
  _y_min_type y_min;

   typedef float _y_max_type;
  _y_max_type y_max;

   typedef float _z_min_type;
  _z_min_type z_min;

   typedef float _z_max_type;
  _z_max_type z_max;

   typedef float _roll_start_type;
  _roll_start_type roll_start;

   typedef float _roll_mid_type;
  _roll_mid_type roll_mid;

   typedef float _roll_end_type;
  _roll_end_type roll_end;

   typedef float _pitch_start_type;
  _pitch_start_type pitch_start;

   typedef float _pitch_mid_type;
  _pitch_mid_type pitch_mid;

   typedef float _pitch_end_type;
  _pitch_end_type pitch_end;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::maneuver::Ellipse5DRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maneuver::Ellipse5DRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Ellipse5DRequest_

typedef ::maneuver::Ellipse5DRequest_<std::allocator<void> > Ellipse5DRequest;

typedef boost::shared_ptr< ::maneuver::Ellipse5DRequest > Ellipse5DRequestPtr;
typedef boost::shared_ptr< ::maneuver::Ellipse5DRequest const> Ellipse5DRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maneuver::Ellipse5DRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maneuver::Ellipse5DRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maneuver::Ellipse5DRequest_<ContainerAllocator1> & lhs, const ::maneuver::Ellipse5DRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x_min == rhs.x_min &&
    lhs.x_max == rhs.x_max &&
    lhs.y_min == rhs.y_min &&
    lhs.y_max == rhs.y_max &&
    lhs.z_min == rhs.z_min &&
    lhs.z_max == rhs.z_max &&
    lhs.roll_start == rhs.roll_start &&
    lhs.roll_mid == rhs.roll_mid &&
    lhs.roll_end == rhs.roll_end &&
    lhs.pitch_start == rhs.pitch_start &&
    lhs.pitch_mid == rhs.pitch_mid &&
    lhs.pitch_end == rhs.pitch_end &&
    lhs.yaw == rhs.yaw &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maneuver::Ellipse5DRequest_<ContainerAllocator1> & lhs, const ::maneuver::Ellipse5DRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maneuver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maneuver::Ellipse5DRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maneuver::Ellipse5DRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::Ellipse5DRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::Ellipse5DRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::Ellipse5DRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::Ellipse5DRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maneuver::Ellipse5DRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de591e0b342372a5677c5ef03c671935";
  }

  static const char* value(const ::maneuver::Ellipse5DRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde591e0b342372a5ULL;
  static const uint64_t static_value2 = 0x677c5ef03c671935ULL;
};

template<class ContainerAllocator>
struct DataType< ::maneuver::Ellipse5DRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maneuver/Ellipse5DRequest";
  }

  static const char* value(const ::maneuver::Ellipse5DRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maneuver::Ellipse5DRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x_min\n"
"float32 x_max\n"
"float32 y_min\n"
"float32 y_max\n"
"float32 z_min\n"
"float32 z_max\n"
"float32 roll_start\n"
"float32 roll_mid\n"
"float32 roll_end\n"
"float32 pitch_start\n"
"float32 pitch_mid\n"
"float32 pitch_end\n"
"float32 yaw\n"
"float32 duration\n"
;
  }

  static const char* value(const ::maneuver::Ellipse5DRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maneuver::Ellipse5DRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_min);
      stream.next(m.x_max);
      stream.next(m.y_min);
      stream.next(m.y_max);
      stream.next(m.z_min);
      stream.next(m.z_max);
      stream.next(m.roll_start);
      stream.next(m.roll_mid);
      stream.next(m.roll_end);
      stream.next(m.pitch_start);
      stream.next(m.pitch_mid);
      stream.next(m.pitch_end);
      stream.next(m.yaw);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ellipse5DRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maneuver::Ellipse5DRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maneuver::Ellipse5DRequest_<ContainerAllocator>& v)
  {
    s << indent << "x_min: ";
    Printer<float>::stream(s, indent + "  ", v.x_min);
    s << indent << "x_max: ";
    Printer<float>::stream(s, indent + "  ", v.x_max);
    s << indent << "y_min: ";
    Printer<float>::stream(s, indent + "  ", v.y_min);
    s << indent << "y_max: ";
    Printer<float>::stream(s, indent + "  ", v.y_max);
    s << indent << "z_min: ";
    Printer<float>::stream(s, indent + "  ", v.z_min);
    s << indent << "z_max: ";
    Printer<float>::stream(s, indent + "  ", v.z_max);
    s << indent << "roll_start: ";
    Printer<float>::stream(s, indent + "  ", v.roll_start);
    s << indent << "roll_mid: ";
    Printer<float>::stream(s, indent + "  ", v.roll_mid);
    s << indent << "roll_end: ";
    Printer<float>::stream(s, indent + "  ", v.roll_end);
    s << indent << "pitch_start: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_start);
    s << indent << "pitch_mid: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_mid);
    s << indent << "pitch_end: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_end);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANEUVER_MESSAGE_ELLIPSE5DREQUEST_H
