// Generated by gencpp from file maneuver/FullFlip.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_FULLFLIP_H
#define MANEUVER_MESSAGE_FULLFLIP_H

#include <ros/service_traits.h>


#include <maneuver/FullFlipRequest.h>
#include <maneuver/FullFlipResponse.h>


namespace maneuver
{

struct FullFlip
{

typedef FullFlipRequest Request;
typedef FullFlipResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FullFlip
} // namespace maneuver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maneuver::FullFlip > {
  static const char* value()
  {
    return "432212f34386b2b3d536658964c298f8";
  }

  static const char* value(const ::maneuver::FullFlip&) { return value(); }
};

template<>
struct DataType< ::maneuver::FullFlip > {
  static const char* value()
  {
    return "maneuver/FullFlip";
  }

  static const char* value(const ::maneuver::FullFlip&) { return value(); }
};


// service_traits::MD5Sum< ::maneuver::FullFlipRequest> should match
// service_traits::MD5Sum< ::maneuver::FullFlip >
template<>
struct MD5Sum< ::maneuver::FullFlipRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::FullFlip >::value();
  }
  static const char* value(const ::maneuver::FullFlipRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::FullFlipRequest> should match
// service_traits::DataType< ::maneuver::FullFlip >
template<>
struct DataType< ::maneuver::FullFlipRequest>
{
  static const char* value()
  {
    return DataType< ::maneuver::FullFlip >::value();
  }
  static const char* value(const ::maneuver::FullFlipRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maneuver::FullFlipResponse> should match
// service_traits::MD5Sum< ::maneuver::FullFlip >
template<>
struct MD5Sum< ::maneuver::FullFlipResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::FullFlip >::value();
  }
  static const char* value(const ::maneuver::FullFlipResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::FullFlipResponse> should match
// service_traits::DataType< ::maneuver::FullFlip >
template<>
struct DataType< ::maneuver::FullFlipResponse>
{
  static const char* value()
  {
    return DataType< ::maneuver::FullFlip >::value();
  }
  static const char* value(const ::maneuver::FullFlipResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANEUVER_MESSAGE_FULLFLIP_H
