// Generated by gencpp from file maneuver/FullFlipRequest.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_FULLFLIPREQUEST_H
#define MANEUVER_MESSAGE_FULLFLIPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maneuver
{
template <class ContainerAllocator>
struct FullFlipRequest_
{
  typedef FullFlipRequest_<ContainerAllocator> Type;

  FullFlipRequest_()
    : roll_bool(false)
    , pitch_bool(false)
    , duration(0.0)  {
    }
  FullFlipRequest_(const ContainerAllocator& _alloc)
    : roll_bool(false)
    , pitch_bool(false)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _roll_bool_type;
  _roll_bool_type roll_bool;

   typedef uint8_t _pitch_bool_type;
  _pitch_bool_type pitch_bool;

   typedef float _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::maneuver::FullFlipRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maneuver::FullFlipRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FullFlipRequest_

typedef ::maneuver::FullFlipRequest_<std::allocator<void> > FullFlipRequest;

typedef boost::shared_ptr< ::maneuver::FullFlipRequest > FullFlipRequestPtr;
typedef boost::shared_ptr< ::maneuver::FullFlipRequest const> FullFlipRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maneuver::FullFlipRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maneuver::FullFlipRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maneuver::FullFlipRequest_<ContainerAllocator1> & lhs, const ::maneuver::FullFlipRequest_<ContainerAllocator2> & rhs)
{
  return lhs.roll_bool == rhs.roll_bool &&
    lhs.pitch_bool == rhs.pitch_bool &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maneuver::FullFlipRequest_<ContainerAllocator1> & lhs, const ::maneuver::FullFlipRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maneuver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maneuver::FullFlipRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maneuver::FullFlipRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::FullFlipRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::FullFlipRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::FullFlipRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::FullFlipRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maneuver::FullFlipRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a2170e847c498f1e2ea30d6f945867c";
  }

  static const char* value(const ::maneuver::FullFlipRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a2170e847c498f1ULL;
  static const uint64_t static_value2 = 0xe2ea30d6f945867cULL;
};

template<class ContainerAllocator>
struct DataType< ::maneuver::FullFlipRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maneuver/FullFlipRequest";
  }

  static const char* value(const ::maneuver::FullFlipRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maneuver::FullFlipRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool roll_bool\n"
"bool pitch_bool\n"
"float32 duration\n"
;
  }

  static const char* value(const ::maneuver::FullFlipRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maneuver::FullFlipRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll_bool);
      stream.next(m.pitch_bool);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FullFlipRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maneuver::FullFlipRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maneuver::FullFlipRequest_<ContainerAllocator>& v)
  {
    s << indent << "roll_bool: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.roll_bool);
    s << indent << "pitch_bool: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pitch_bool);
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANEUVER_MESSAGE_FULLFLIPREQUEST_H
