// Generated by gencpp from file maneuver/Goto6DPoint.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_GOTO6DPOINT_H
#define MANEUVER_MESSAGE_GOTO6DPOINT_H

#include <ros/service_traits.h>


#include <maneuver/Goto6DPointRequest.h>
#include <maneuver/Goto6DPointResponse.h>


namespace maneuver
{

struct Goto6DPoint
{

typedef Goto6DPointRequest Request;
typedef Goto6DPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Goto6DPoint
} // namespace maneuver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maneuver::Goto6DPoint > {
  static const char* value()
  {
    return "ceed9bb0a85fabd7e22e37d55fef957b";
  }

  static const char* value(const ::maneuver::Goto6DPoint&) { return value(); }
};

template<>
struct DataType< ::maneuver::Goto6DPoint > {
  static const char* value()
  {
    return "maneuver/Goto6DPoint";
  }

  static const char* value(const ::maneuver::Goto6DPoint&) { return value(); }
};


// service_traits::MD5Sum< ::maneuver::Goto6DPointRequest> should match
// service_traits::MD5Sum< ::maneuver::Goto6DPoint >
template<>
struct MD5Sum< ::maneuver::Goto6DPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::Goto6DPoint >::value();
  }
  static const char* value(const ::maneuver::Goto6DPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::Goto6DPointRequest> should match
// service_traits::DataType< ::maneuver::Goto6DPoint >
template<>
struct DataType< ::maneuver::Goto6DPointRequest>
{
  static const char* value()
  {
    return DataType< ::maneuver::Goto6DPoint >::value();
  }
  static const char* value(const ::maneuver::Goto6DPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maneuver::Goto6DPointResponse> should match
// service_traits::MD5Sum< ::maneuver::Goto6DPoint >
template<>
struct MD5Sum< ::maneuver::Goto6DPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::Goto6DPoint >::value();
  }
  static const char* value(const ::maneuver::Goto6DPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::Goto6DPointResponse> should match
// service_traits::DataType< ::maneuver::Goto6DPoint >
template<>
struct DataType< ::maneuver::Goto6DPointResponse>
{
  static const char* value()
  {
    return DataType< ::maneuver::Goto6DPoint >::value();
  }
  static const char* value(const ::maneuver::Goto6DPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANEUVER_MESSAGE_GOTO6DPOINT_H
