// Generated by gencpp from file maneuver/GotoPointRequest.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_GOTOPOINTREQUEST_H
#define MANEUVER_MESSAGE_GOTOPOINTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maneuver
{
template <class ContainerAllocator>
struct GotoPointRequest_
{
  typedef GotoPointRequest_<ContainerAllocator> Type;

  GotoPointRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , duration(0.0)  {
    }
  GotoPointRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::maneuver::GotoPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maneuver::GotoPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GotoPointRequest_

typedef ::maneuver::GotoPointRequest_<std::allocator<void> > GotoPointRequest;

typedef boost::shared_ptr< ::maneuver::GotoPointRequest > GotoPointRequestPtr;
typedef boost::shared_ptr< ::maneuver::GotoPointRequest const> GotoPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maneuver::GotoPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maneuver::GotoPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maneuver::GotoPointRequest_<ContainerAllocator1> & lhs, const ::maneuver::GotoPointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.yaw == rhs.yaw &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maneuver::GotoPointRequest_<ContainerAllocator1> & lhs, const ::maneuver::GotoPointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maneuver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maneuver::GotoPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maneuver::GotoPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::GotoPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::GotoPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::GotoPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::GotoPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maneuver::GotoPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f3dce280bda63de9570d588ac3fe54a";
  }

  static const char* value(const ::maneuver::GotoPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f3dce280bda63deULL;
  static const uint64_t static_value2 = 0x9570d588ac3fe54aULL;
};

template<class ContainerAllocator>
struct DataType< ::maneuver::GotoPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maneuver/GotoPointRequest";
  }

  static const char* value(const ::maneuver::GotoPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maneuver::GotoPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 yaw\n"
"float32 duration\n"
;
  }

  static const char* value(const ::maneuver::GotoPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maneuver::GotoPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GotoPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maneuver::GotoPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maneuver::GotoPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANEUVER_MESSAGE_GOTOPOINTREQUEST_H
