// Generated by gencpp from file maneuver/Goto6DPointRequest.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_GOTO6DPOINTREQUEST_H
#define MANEUVER_MESSAGE_GOTO6DPOINTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maneuver
{
template <class ContainerAllocator>
struct Goto6DPointRequest_
{
  typedef Goto6DPointRequest_<ContainerAllocator> Type;

  Goto6DPointRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , duration(0.0)  {
    }
  Goto6DPointRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::maneuver::Goto6DPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maneuver::Goto6DPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Goto6DPointRequest_

typedef ::maneuver::Goto6DPointRequest_<std::allocator<void> > Goto6DPointRequest;

typedef boost::shared_ptr< ::maneuver::Goto6DPointRequest > Goto6DPointRequestPtr;
typedef boost::shared_ptr< ::maneuver::Goto6DPointRequest const> Goto6DPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maneuver::Goto6DPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maneuver::Goto6DPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maneuver::Goto6DPointRequest_<ContainerAllocator1> & lhs, const ::maneuver::Goto6DPointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maneuver::Goto6DPointRequest_<ContainerAllocator1> & lhs, const ::maneuver::Goto6DPointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maneuver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maneuver::Goto6DPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maneuver::Goto6DPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::Goto6DPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::Goto6DPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::Goto6DPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::Goto6DPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maneuver::Goto6DPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8429e9701fca716c448b97f0f571e22c";
  }

  static const char* value(const ::maneuver::Goto6DPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8429e9701fca716cULL;
  static const uint64_t static_value2 = 0x448b97f0f571e22cULL;
};

template<class ContainerAllocator>
struct DataType< ::maneuver::Goto6DPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maneuver/Goto6DPointRequest";
  }

  static const char* value(const ::maneuver::Goto6DPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maneuver::Goto6DPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
"float32 duration\n"
;
  }

  static const char* value(const ::maneuver::Goto6DPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maneuver::Goto6DPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Goto6DPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maneuver::Goto6DPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maneuver::Goto6DPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANEUVER_MESSAGE_GOTO6DPOINTREQUEST_H
