// Generated by gencpp from file maneuver/GotoPoint.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_GOTOPOINT_H
#define MANEUVER_MESSAGE_GOTOPOINT_H

#include <ros/service_traits.h>


#include <maneuver/GotoPointRequest.h>
#include <maneuver/GotoPointResponse.h>


namespace maneuver
{

struct GotoPoint
{

typedef GotoPointRequest Request;
typedef GotoPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GotoPoint
} // namespace maneuver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maneuver::GotoPoint > {
  static const char* value()
  {
    return "13a22628e95c1b6dce035f4797b346a3";
  }

  static const char* value(const ::maneuver::GotoPoint&) { return value(); }
};

template<>
struct DataType< ::maneuver::GotoPoint > {
  static const char* value()
  {
    return "maneuver/GotoPoint";
  }

  static const char* value(const ::maneuver::GotoPoint&) { return value(); }
};


// service_traits::MD5Sum< ::maneuver::GotoPointRequest> should match
// service_traits::MD5Sum< ::maneuver::GotoPoint >
template<>
struct MD5Sum< ::maneuver::GotoPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::GotoPoint >::value();
  }
  static const char* value(const ::maneuver::GotoPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::GotoPointRequest> should match
// service_traits::DataType< ::maneuver::GotoPoint >
template<>
struct DataType< ::maneuver::GotoPointRequest>
{
  static const char* value()
  {
    return DataType< ::maneuver::GotoPoint >::value();
  }
  static const char* value(const ::maneuver::GotoPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maneuver::GotoPointResponse> should match
// service_traits::MD5Sum< ::maneuver::GotoPoint >
template<>
struct MD5Sum< ::maneuver::GotoPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::GotoPoint >::value();
  }
  static const char* value(const ::maneuver::GotoPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::GotoPointResponse> should match
// service_traits::DataType< ::maneuver::GotoPoint >
template<>
struct DataType< ::maneuver::GotoPointResponse>
{
  static const char* value()
  {
    return DataType< ::maneuver::GotoPoint >::value();
  }
  static const char* value(const ::maneuver::GotoPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANEUVER_MESSAGE_GOTOPOINT_H
