// Generated by gencpp from file maneuver/Land.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_LAND_H
#define MANEUVER_MESSAGE_LAND_H

#include <ros/service_traits.h>


#include <maneuver/LandRequest.h>
#include <maneuver/LandResponse.h>


namespace maneuver
{

struct Land
{

typedef LandRequest Request;
typedef LandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Land
} // namespace maneuver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maneuver::Land > {
  static const char* value()
  {
    return "6caadcbcd5d54204c00f1a33593265c7";
  }

  static const char* value(const ::maneuver::Land&) { return value(); }
};

template<>
struct DataType< ::maneuver::Land > {
  static const char* value()
  {
    return "maneuver/Land";
  }

  static const char* value(const ::maneuver::Land&) { return value(); }
};


// service_traits::MD5Sum< ::maneuver::LandRequest> should match
// service_traits::MD5Sum< ::maneuver::Land >
template<>
struct MD5Sum< ::maneuver::LandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::Land >::value();
  }
  static const char* value(const ::maneuver::LandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::LandRequest> should match
// service_traits::DataType< ::maneuver::Land >
template<>
struct DataType< ::maneuver::LandRequest>
{
  static const char* value()
  {
    return DataType< ::maneuver::Land >::value();
  }
  static const char* value(const ::maneuver::LandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maneuver::LandResponse> should match
// service_traits::MD5Sum< ::maneuver::Land >
template<>
struct MD5Sum< ::maneuver::LandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::Land >::value();
  }
  static const char* value(const ::maneuver::LandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::LandResponse> should match
// service_traits::DataType< ::maneuver::Land >
template<>
struct DataType< ::maneuver::LandResponse>
{
  static const char* value()
  {
    return DataType< ::maneuver::Land >::value();
  }
  static const char* value(const ::maneuver::LandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANEUVER_MESSAGE_LAND_H
