// Generated by gencpp from file maneuver/LandRequest.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_LANDREQUEST_H
#define MANEUVER_MESSAGE_LANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maneuver
{
template <class ContainerAllocator>
struct LandRequest_
{
  typedef LandRequest_<ContainerAllocator> Type;

  LandRequest_()
    : height_1(0.0)
    , duration_1(0.0)
    , height_2(0.0)
    , duration_2(0.0)  {
    }
  LandRequest_(const ContainerAllocator& _alloc)
    : height_1(0.0)
    , duration_1(0.0)
    , height_2(0.0)
    , duration_2(0.0)  {
  (void)_alloc;
    }



   typedef float _height_1_type;
  _height_1_type height_1;

   typedef float _duration_1_type;
  _duration_1_type duration_1;

   typedef float _height_2_type;
  _height_2_type height_2;

   typedef float _duration_2_type;
  _duration_2_type duration_2;





  typedef boost::shared_ptr< ::maneuver::LandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maneuver::LandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LandRequest_

typedef ::maneuver::LandRequest_<std::allocator<void> > LandRequest;

typedef boost::shared_ptr< ::maneuver::LandRequest > LandRequestPtr;
typedef boost::shared_ptr< ::maneuver::LandRequest const> LandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maneuver::LandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maneuver::LandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maneuver::LandRequest_<ContainerAllocator1> & lhs, const ::maneuver::LandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.height_1 == rhs.height_1 &&
    lhs.duration_1 == rhs.duration_1 &&
    lhs.height_2 == rhs.height_2 &&
    lhs.duration_2 == rhs.duration_2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maneuver::LandRequest_<ContainerAllocator1> & lhs, const ::maneuver::LandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maneuver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maneuver::LandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maneuver::LandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::LandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::LandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::LandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::LandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maneuver::LandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32263ce3c47b5e10a67905c677fd1816";
  }

  static const char* value(const ::maneuver::LandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32263ce3c47b5e10ULL;
  static const uint64_t static_value2 = 0xa67905c677fd1816ULL;
};

template<class ContainerAllocator>
struct DataType< ::maneuver::LandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maneuver/LandRequest";
  }

  static const char* value(const ::maneuver::LandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maneuver::LandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 height_1\n"
"float32 duration_1\n"
"float32 height_2\n"
"float32 duration_2\n"
;
  }

  static const char* value(const ::maneuver::LandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maneuver::LandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height_1);
      stream.next(m.duration_1);
      stream.next(m.height_2);
      stream.next(m.duration_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maneuver::LandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maneuver::LandRequest_<ContainerAllocator>& v)
  {
    s << indent << "height_1: ";
    Printer<float>::stream(s, indent + "  ", v.height_1);
    s << indent << "duration_1: ";
    Printer<float>::stream(s, indent + "  ", v.duration_1);
    s << indent << "height_2: ";
    Printer<float>::stream(s, indent + "  ", v.height_2);
    s << indent << "duration_2: ";
    Printer<float>::stream(s, indent + "  ", v.duration_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANEUVER_MESSAGE_LANDREQUEST_H
