// Generated by gencpp from file maneuver/LiftOffRequest.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_LIFTOFFREQUEST_H
#define MANEUVER_MESSAGE_LIFTOFFREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maneuver
{
template <class ContainerAllocator>
struct LiftOffRequest_
{
  typedef LiftOffRequest_<ContainerAllocator> Type;

  LiftOffRequest_()
    : height(0.0)
    , duration(0.0)  {
    }
  LiftOffRequest_(const ContainerAllocator& _alloc)
    : height(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef float _height_type;
  _height_type height;

   typedef float _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::maneuver::LiftOffRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maneuver::LiftOffRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LiftOffRequest_

typedef ::maneuver::LiftOffRequest_<std::allocator<void> > LiftOffRequest;

typedef boost::shared_ptr< ::maneuver::LiftOffRequest > LiftOffRequestPtr;
typedef boost::shared_ptr< ::maneuver::LiftOffRequest const> LiftOffRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maneuver::LiftOffRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maneuver::LiftOffRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maneuver::LiftOffRequest_<ContainerAllocator1> & lhs, const ::maneuver::LiftOffRequest_<ContainerAllocator2> & rhs)
{
  return lhs.height == rhs.height &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maneuver::LiftOffRequest_<ContainerAllocator1> & lhs, const ::maneuver::LiftOffRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maneuver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maneuver::LiftOffRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maneuver::LiftOffRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::LiftOffRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::LiftOffRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::LiftOffRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::LiftOffRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maneuver::LiftOffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3adf5fdee89cbeb13819b3887ee605eb";
  }

  static const char* value(const ::maneuver::LiftOffRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3adf5fdee89cbeb1ULL;
  static const uint64_t static_value2 = 0x3819b3887ee605ebULL;
};

template<class ContainerAllocator>
struct DataType< ::maneuver::LiftOffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maneuver/LiftOffRequest";
  }

  static const char* value(const ::maneuver::LiftOffRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maneuver::LiftOffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 height\n"
"float32 duration\n"
;
  }

  static const char* value(const ::maneuver::LiftOffRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maneuver::LiftOffRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LiftOffRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maneuver::LiftOffRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maneuver::LiftOffRequest_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANEUVER_MESSAGE_LIFTOFFREQUEST_H
