// Generated by gencpp from file maneuver/LiftOff.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_LIFTOFF_H
#define MANEUVER_MESSAGE_LIFTOFF_H

#include <ros/service_traits.h>


#include <maneuver/LiftOffRequest.h>
#include <maneuver/LiftOffResponse.h>


namespace maneuver
{

struct LiftOff
{

typedef LiftOffRequest Request;
typedef LiftOffResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LiftOff
} // namespace maneuver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maneuver::LiftOff > {
  static const char* value()
  {
    return "9e16cfae3e3728d84a285e6768841653";
  }

  static const char* value(const ::maneuver::LiftOff&) { return value(); }
};

template<>
struct DataType< ::maneuver::LiftOff > {
  static const char* value()
  {
    return "maneuver/LiftOff";
  }

  static const char* value(const ::maneuver::LiftOff&) { return value(); }
};


// service_traits::MD5Sum< ::maneuver::LiftOffRequest> should match
// service_traits::MD5Sum< ::maneuver::LiftOff >
template<>
struct MD5Sum< ::maneuver::LiftOffRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::LiftOff >::value();
  }
  static const char* value(const ::maneuver::LiftOffRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::LiftOffRequest> should match
// service_traits::DataType< ::maneuver::LiftOff >
template<>
struct DataType< ::maneuver::LiftOffRequest>
{
  static const char* value()
  {
    return DataType< ::maneuver::LiftOff >::value();
  }
  static const char* value(const ::maneuver::LiftOffRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maneuver::LiftOffResponse> should match
// service_traits::MD5Sum< ::maneuver::LiftOff >
template<>
struct MD5Sum< ::maneuver::LiftOffResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::LiftOff >::value();
  }
  static const char* value(const ::maneuver::LiftOffResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::LiftOffResponse> should match
// service_traits::DataType< ::maneuver::LiftOff >
template<>
struct DataType< ::maneuver::LiftOffResponse>
{
  static const char* value()
  {
    return DataType< ::maneuver::LiftOff >::value();
  }
  static const char* value(const ::maneuver::LiftOffResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANEUVER_MESSAGE_LIFTOFF_H
