// Generated by gencpp from file maneuver/RotateTo.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_ROTATETO_H
#define MANEUVER_MESSAGE_ROTATETO_H

#include <ros/service_traits.h>


#include <maneuver/RotateToRequest.h>
#include <maneuver/RotateToResponse.h>


namespace maneuver
{

struct RotateTo
{

typedef RotateToRequest Request;
typedef RotateToResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RotateTo
} // namespace maneuver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::maneuver::RotateTo > {
  static const char* value()
  {
    return "e91f34039ff130f224ba3462d670a1d0";
  }

  static const char* value(const ::maneuver::RotateTo&) { return value(); }
};

template<>
struct DataType< ::maneuver::RotateTo > {
  static const char* value()
  {
    return "maneuver/RotateTo";
  }

  static const char* value(const ::maneuver::RotateTo&) { return value(); }
};


// service_traits::MD5Sum< ::maneuver::RotateToRequest> should match
// service_traits::MD5Sum< ::maneuver::RotateTo >
template<>
struct MD5Sum< ::maneuver::RotateToRequest>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::RotateTo >::value();
  }
  static const char* value(const ::maneuver::RotateToRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::RotateToRequest> should match
// service_traits::DataType< ::maneuver::RotateTo >
template<>
struct DataType< ::maneuver::RotateToRequest>
{
  static const char* value()
  {
    return DataType< ::maneuver::RotateTo >::value();
  }
  static const char* value(const ::maneuver::RotateToRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::maneuver::RotateToResponse> should match
// service_traits::MD5Sum< ::maneuver::RotateTo >
template<>
struct MD5Sum< ::maneuver::RotateToResponse>
{
  static const char* value()
  {
    return MD5Sum< ::maneuver::RotateTo >::value();
  }
  static const char* value(const ::maneuver::RotateToResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::maneuver::RotateToResponse> should match
// service_traits::DataType< ::maneuver::RotateTo >
template<>
struct DataType< ::maneuver::RotateToResponse>
{
  static const char* value()
  {
    return DataType< ::maneuver::RotateTo >::value();
  }
  static const char* value(const ::maneuver::RotateToResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANEUVER_MESSAGE_ROTATETO_H
