// Generated by gencpp from file maneuver/RotateToRequest.msg
// DO NOT EDIT!


#ifndef MANEUVER_MESSAGE_ROTATETOREQUEST_H
#define MANEUVER_MESSAGE_ROTATETOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maneuver
{
template <class ContainerAllocator>
struct RotateToRequest_
{
  typedef RotateToRequest_<ContainerAllocator> Type;

  RotateToRequest_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , duration(0.0)  {
    }
  RotateToRequest_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::maneuver::RotateToRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maneuver::RotateToRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RotateToRequest_

typedef ::maneuver::RotateToRequest_<std::allocator<void> > RotateToRequest;

typedef boost::shared_ptr< ::maneuver::RotateToRequest > RotateToRequestPtr;
typedef boost::shared_ptr< ::maneuver::RotateToRequest const> RotateToRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maneuver::RotateToRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maneuver::RotateToRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maneuver::RotateToRequest_<ContainerAllocator1> & lhs, const ::maneuver::RotateToRequest_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maneuver::RotateToRequest_<ContainerAllocator1> & lhs, const ::maneuver::RotateToRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maneuver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maneuver::RotateToRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maneuver::RotateToRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::RotateToRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maneuver::RotateToRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::RotateToRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maneuver::RotateToRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maneuver::RotateToRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6c66a74ccfb8053a0ecaed4658159bd";
  }

  static const char* value(const ::maneuver::RotateToRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6c66a74ccfb8053ULL;
  static const uint64_t static_value2 = 0xa0ecaed4658159bdULL;
};

template<class ContainerAllocator>
struct DataType< ::maneuver::RotateToRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maneuver/RotateToRequest";
  }

  static const char* value(const ::maneuver::RotateToRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maneuver::RotateToRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
"float32 duration\n"
;
  }

  static const char* value(const ::maneuver::RotateToRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maneuver::RotateToRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RotateToRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maneuver::RotateToRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maneuver::RotateToRequest_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANEUVER_MESSAGE_ROTATETOREQUEST_H
