// Generated by gencpp from file omni_firmware/errorMsg.msg
// DO NOT EDIT!


#ifndef OMNI_FIRMWARE_MESSAGE_ERRORMSG_H
#define OMNI_FIRMWARE_MESSAGE_ERRORMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace omni_firmware
{
template <class ContainerAllocator>
struct errorMsg_
{
  typedef errorMsg_<ContainerAllocator> Type;

  errorMsg_()
    : ex()
    , ev()
    , ea()
    , eR()
    , ew()
    , Iex()
    , Ier()
    , Accd()
    , Wrench()
    , exWrench()
    , prop()
    , weight(0.0)  {
    }
  errorMsg_(const ContainerAllocator& _alloc)
    : ex(_alloc)
    , ev(_alloc)
    , ea(_alloc)
    , eR(_alloc)
    , ew(_alloc)
    , Iex(_alloc)
    , Ier(_alloc)
    , Accd(_alloc)
    , Wrench(_alloc)
    , exWrench(_alloc)
    , prop(_alloc)
    , weight(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ex_type;
  _ex_type ex;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ev_type;
  _ev_type ev;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ea_type;
  _ea_type ea;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _eR_type;
  _eR_type eR;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ew_type;
  _ew_type ew;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _Iex_type;
  _Iex_type Iex;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _Ier_type;
  _Ier_type Ier;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _Accd_type;
  _Accd_type Accd;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _Wrench_type;
  _Wrench_type Wrench;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _exWrench_type;
  _exWrench_type exWrench;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _prop_type;
  _prop_type prop;

   typedef float _weight_type;
  _weight_type weight;





  typedef boost::shared_ptr< ::omni_firmware::errorMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omni_firmware::errorMsg_<ContainerAllocator> const> ConstPtr;

}; // struct errorMsg_

typedef ::omni_firmware::errorMsg_<std::allocator<void> > errorMsg;

typedef boost::shared_ptr< ::omni_firmware::errorMsg > errorMsgPtr;
typedef boost::shared_ptr< ::omni_firmware::errorMsg const> errorMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omni_firmware::errorMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omni_firmware::errorMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::omni_firmware::errorMsg_<ContainerAllocator1> & lhs, const ::omni_firmware::errorMsg_<ContainerAllocator2> & rhs)
{
  return lhs.ex == rhs.ex &&
    lhs.ev == rhs.ev &&
    lhs.ea == rhs.ea &&
    lhs.eR == rhs.eR &&
    lhs.ew == rhs.ew &&
    lhs.Iex == rhs.Iex &&
    lhs.Ier == rhs.Ier &&
    lhs.Accd == rhs.Accd &&
    lhs.Wrench == rhs.Wrench &&
    lhs.exWrench == rhs.exWrench &&
    lhs.prop == rhs.prop &&
    lhs.weight == rhs.weight;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::omni_firmware::errorMsg_<ContainerAllocator1> & lhs, const ::omni_firmware::errorMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace omni_firmware

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::omni_firmware::errorMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omni_firmware::errorMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omni_firmware::errorMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omni_firmware::errorMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omni_firmware::errorMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omni_firmware::errorMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omni_firmware::errorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aca7c5154e5df4742f8034562501f6c5";
  }

  static const char* value(const ::omni_firmware::errorMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaca7c5154e5df474ULL;
  static const uint64_t static_value2 = 0x2f8034562501f6c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::omni_firmware::errorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omni_firmware/errorMsg";
  }

  static const char* value(const ::omni_firmware::errorMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omni_firmware::errorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 ex\n"
"geometry_msgs/Vector3 ev\n"
"geometry_msgs/Vector3 ea\n"
"geometry_msgs/Vector3 eR\n"
"geometry_msgs/Vector3 ew\n"
"geometry_msgs/Vector3 Iex\n"
"geometry_msgs/Vector3 Ier\n"
"geometry_msgs/Vector3 Accd\n"
"float32[] Wrench\n"
"float32[] exWrench\n"
"float32[] prop\n"
"float32 weight\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::omni_firmware::errorMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omni_firmware::errorMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ex);
      stream.next(m.ev);
      stream.next(m.ea);
      stream.next(m.eR);
      stream.next(m.ew);
      stream.next(m.Iex);
      stream.next(m.Ier);
      stream.next(m.Accd);
      stream.next(m.Wrench);
      stream.next(m.exWrench);
      stream.next(m.prop);
      stream.next(m.weight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct errorMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omni_firmware::errorMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::omni_firmware::errorMsg_<ContainerAllocator>& v)
  {
    s << indent << "ex: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ex);
    s << indent << "ev: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ev);
    s << indent << "ea: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ea);
    s << indent << "eR: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.eR);
    s << indent << "ew: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ew);
    s << indent << "Iex: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.Iex);
    s << indent << "Ier: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.Ier);
    s << indent << "Accd: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.Accd);
    s << indent << "Wrench[]" << std::endl;
    for (size_t i = 0; i < v.Wrench.size(); ++i)
    {
      s << indent << "  Wrench[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.Wrench[i]);
    }
    s << indent << "exWrench[]" << std::endl;
    for (size_t i = 0; i < v.exWrench.size(); ++i)
    {
      s << indent << "  exWrench[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.exWrench[i]);
    }
    s << indent << "prop[]" << std::endl;
    for (size_t i = 0; i < v.prop.size(); ++i)
    {
      s << indent << "  prop[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.prop[i]);
    }
    s << indent << "weight: ";
    Printer<float>::stream(s, indent + "  ", v.weight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMNI_FIRMWARE_MESSAGE_ERRORMSG_H
