// Generated by gencpp from file omni_firmware/MotorSpeed.msg
// DO NOT EDIT!


#ifndef OMNI_FIRMWARE_MESSAGE_MOTORSPEED_H
#define OMNI_FIRMWARE_MESSAGE_MOTORSPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace omni_firmware
{
template <class ContainerAllocator>
struct MotorSpeed_
{
  typedef MotorSpeed_<ContainerAllocator> Type;

  MotorSpeed_()
    : name()
    , velocity()  {
    }
  MotorSpeed_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , velocity(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _name_type;
  _name_type name;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::omni_firmware::MotorSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omni_firmware::MotorSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct MotorSpeed_

typedef ::omni_firmware::MotorSpeed_<std::allocator<void> > MotorSpeed;

typedef boost::shared_ptr< ::omni_firmware::MotorSpeed > MotorSpeedPtr;
typedef boost::shared_ptr< ::omni_firmware::MotorSpeed const> MotorSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omni_firmware::MotorSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omni_firmware::MotorSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::omni_firmware::MotorSpeed_<ContainerAllocator1> & lhs, const ::omni_firmware::MotorSpeed_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::omni_firmware::MotorSpeed_<ContainerAllocator1> & lhs, const ::omni_firmware::MotorSpeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace omni_firmware

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::omni_firmware::MotorSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omni_firmware::MotorSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omni_firmware::MotorSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omni_firmware::MotorSpeed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omni_firmware::MotorSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omni_firmware::MotorSpeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omni_firmware::MotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1d54c3c8a939a204eb96629420d7ab7";
  }

  static const char* value(const ::omni_firmware::MotorSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1d54c3c8a939a20ULL;
  static const uint64_t static_value2 = 0x4eb96629420d7ab7ULL;
};

template<class ContainerAllocator>
struct DataType< ::omni_firmware::MotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omni_firmware/MotorSpeed";
  }

  static const char* value(const ::omni_firmware::MotorSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omni_firmware::MotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] name\n"
"float32[] velocity\n"
;
  }

  static const char* value(const ::omni_firmware::MotorSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omni_firmware::MotorSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omni_firmware::MotorSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::omni_firmware::MotorSpeed_<ContainerAllocator>& v)
  {
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocity[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMNI_FIRMWARE_MESSAGE_MOTORSPEED_H
