// Generated by gencpp from file omni_firmware/Uvector.msg
// DO NOT EDIT!


#ifndef OMNI_FIRMWARE_MESSAGE_UVECTOR_H
#define OMNI_FIRMWARE_MESSAGE_UVECTOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace omni_firmware
{
template <class ContainerAllocator>
struct Uvector_
{
  typedef Uvector_<ContainerAllocator> Type;

  Uvector_()
    : value()  {
      value.assign(0.0);
  }
  Uvector_(const ContainerAllocator& _alloc)
    : value()  {
  (void)_alloc;
      value.assign(0.0);
  }



   typedef boost::array<float, 12>  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::omni_firmware::Uvector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omni_firmware::Uvector_<ContainerAllocator> const> ConstPtr;

}; // struct Uvector_

typedef ::omni_firmware::Uvector_<std::allocator<void> > Uvector;

typedef boost::shared_ptr< ::omni_firmware::Uvector > UvectorPtr;
typedef boost::shared_ptr< ::omni_firmware::Uvector const> UvectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omni_firmware::Uvector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omni_firmware::Uvector_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::omni_firmware::Uvector_<ContainerAllocator1> & lhs, const ::omni_firmware::Uvector_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::omni_firmware::Uvector_<ContainerAllocator1> & lhs, const ::omni_firmware::Uvector_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace omni_firmware

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::omni_firmware::Uvector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omni_firmware::Uvector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omni_firmware::Uvector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omni_firmware::Uvector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omni_firmware::Uvector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omni_firmware::Uvector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omni_firmware::Uvector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cac8a89b50e7d740ace6fafac0a09de";
  }

  static const char* value(const ::omni_firmware::Uvector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cac8a89b50e7d74ULL;
  static const uint64_t static_value2 = 0x0ace6fafac0a09deULL;
};

template<class ContainerAllocator>
struct DataType< ::omni_firmware::Uvector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omni_firmware/Uvector";
  }

  static const char* value(const ::omni_firmware::Uvector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omni_firmware::Uvector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[12] value\n"
;
  }

  static const char* value(const ::omni_firmware::Uvector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omni_firmware::Uvector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Uvector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omni_firmware::Uvector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::omni_firmware::Uvector_<ContainerAllocator>& v)
  {
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMNI_FIRMWARE_MESSAGE_UVECTOR_H
