// Generated by gencpp from file omni_firmware/ZeroUKF.msg
// DO NOT EDIT!


#ifndef OMNI_FIRMWARE_MESSAGE_ZEROUKF_H
#define OMNI_FIRMWARE_MESSAGE_ZEROUKF_H

#include <ros/service_traits.h>


#include <omni_firmware/ZeroUKFRequest.h>
#include <omni_firmware/ZeroUKFResponse.h>


namespace omni_firmware
{

struct ZeroUKF
{

typedef ZeroUKFRequest Request;
typedef ZeroUKFResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ZeroUKF
} // namespace omni_firmware


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::omni_firmware::ZeroUKF > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::omni_firmware::ZeroUKF&) { return value(); }
};

template<>
struct DataType< ::omni_firmware::ZeroUKF > {
  static const char* value()
  {
    return "omni_firmware/ZeroUKF";
  }

  static const char* value(const ::omni_firmware::ZeroUKF&) { return value(); }
};


// service_traits::MD5Sum< ::omni_firmware::ZeroUKFRequest> should match
// service_traits::MD5Sum< ::omni_firmware::ZeroUKF >
template<>
struct MD5Sum< ::omni_firmware::ZeroUKFRequest>
{
  static const char* value()
  {
    return MD5Sum< ::omni_firmware::ZeroUKF >::value();
  }
  static const char* value(const ::omni_firmware::ZeroUKFRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::omni_firmware::ZeroUKFRequest> should match
// service_traits::DataType< ::omni_firmware::ZeroUKF >
template<>
struct DataType< ::omni_firmware::ZeroUKFRequest>
{
  static const char* value()
  {
    return DataType< ::omni_firmware::ZeroUKF >::value();
  }
  static const char* value(const ::omni_firmware::ZeroUKFRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::omni_firmware::ZeroUKFResponse> should match
// service_traits::MD5Sum< ::omni_firmware::ZeroUKF >
template<>
struct MD5Sum< ::omni_firmware::ZeroUKFResponse>
{
  static const char* value()
  {
    return MD5Sum< ::omni_firmware::ZeroUKF >::value();
  }
  static const char* value(const ::omni_firmware::ZeroUKFResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::omni_firmware::ZeroUKFResponse> should match
// service_traits::DataType< ::omni_firmware::ZeroUKF >
template<>
struct DataType< ::omni_firmware::ZeroUKFResponse>
{
  static const char* value()
  {
    return DataType< ::omni_firmware::ZeroUKF >::value();
  }
  static const char* value(const ::omni_firmware::ZeroUKFResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OMNI_FIRMWARE_MESSAGE_ZEROUKF_H
