// Generated by gencpp from file omni_firmware/ZeroUKFRequest.msg
// DO NOT EDIT!


#ifndef OMNI_FIRMWARE_MESSAGE_ZEROUKFREQUEST_H
#define OMNI_FIRMWARE_MESSAGE_ZEROUKFREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace omni_firmware
{
template <class ContainerAllocator>
struct ZeroUKFRequest_
{
  typedef ZeroUKFRequest_<ContainerAllocator> Type;

  ZeroUKFRequest_()
    {
    }
  ZeroUKFRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ZeroUKFRequest_

typedef ::omni_firmware::ZeroUKFRequest_<std::allocator<void> > ZeroUKFRequest;

typedef boost::shared_ptr< ::omni_firmware::ZeroUKFRequest > ZeroUKFRequestPtr;
typedef boost::shared_ptr< ::omni_firmware::ZeroUKFRequest const> ZeroUKFRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace omni_firmware

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::omni_firmware::ZeroUKFRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omni_firmware/ZeroUKFRequest";
  }

  static const char* value(const ::omni_firmware::ZeroUKFRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ZeroRotation.srv\n"
;
  }

  static const char* value(const ::omni_firmware::ZeroUKFRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ZeroUKFRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omni_firmware::ZeroUKFRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::omni_firmware::ZeroUKFRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OMNI_FIRMWARE_MESSAGE_ZEROUKFREQUEST_H
